### ISSUE TITLE
[Crash] [Forge 45.0.40] Game crashed while rendering overlay

### ISSUE THREAD

**Issue by LuineGR** [SuperMartijn642/Rechiseled#26] opened 2023-04-01 20:17 UTC
I meet all required dependencies, and am using the version meant specifically for 1.19.4 according to the CurseForge version tags.

When the game is nearly finished loading, it suddenly quits. The launcher then displays this prompt:
> The game crashed whilst rendering overlay
> Error: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/block/model/ItemTransforms$TransformType

My crash report reads as follows:
```
---- Minecraft Crash Report ----
// Sorry :(

Time: 2023-04-01 17:14:30
Description: Rendering overlay

java.lang.NoClassDefFoundError: net/minecraft/client/renderer/block/model/ItemTransforms$TransformType
	at com.supermartijn642.rechiseled.model.RechiseledModel.getTransforms(RechiseledModel.java:144) ~[rechiseled-1.0.12a-forge-mc1.19.3.jar%23161!/:?] {re:classloading}
	at com.supermartijn642.rechiseled.model.RechiseledModel.bake(RechiseledModel.java:59) ~[rechiseled-1.0.12a-forge-mc1.19.3.jar%23161!/:?] {re:classloading}
	at net.minecraftforge.client.model.geometry.UnbakedGeometryHelper.bake(UnbakedGeometryHelper.java:105) ~[forge-1.19.4-45.0.40-universal.jar%23170!/:?] {re:classloading}
	at net.minecraft.client.renderer.block.model.BlockModel.m_111449_(BlockModel.java:194) ~[client-1.19.4-20230314.122934-srg.jar%23165!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.block.model.BlockModel.m_7611_(BlockModel.java:190) ~[client-1.19.4-20230314.122934-srg.jar%23165!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.resources.model.ModelBakery$ModelBakerImpl.bake(ModelBakery.java:760) ~[client-1.19.4-20230314.122934-srg.jar%23165!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.resources.model.ModelBakery$ModelBakerImpl.m_245240_(ModelBakery.java:732) ~[client-1.19.4-20230314.122934-srg.jar%23165!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.resources.model.ModelBakery.lambda$bakeModels$9(ModelBakery.java:211) ~[client-1.19.4-20230314.122934-srg.jar%23165!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:A}
	at java.util.HashMap$KeySet.forEach(HashMap.java:1008) ~[?:?] {}
	at net.minecraft.client.resources.model.ModelBakery.m_245909_(ModelBakery.java:206) ~[client-1.19.4-20230314.122934-srg.jar%23165!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:A}
	at net.minecraft.client.resources.model.ModelManager.m_245476_(ModelManager.java:158) ~[client-1.19.4-20230314.122934-srg.jar%23165!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.resources.model.ModelManager.m_246937_(ModelManager.java:89) ~[client-1.19.4-20230314.122934-srg.jar%23165!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.block.model.ItemTransforms$TransformType
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-2.1.6.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	... 19 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.supermartijn642.rechiseled.model.RechiseledModel.getTransforms(RechiseledModel.java:144) ~[rechiseled-1.0.12a-forge-mc1.19.3.jar%23161!/:?] {re:classloading}
	at com.supermartijn642.rechiseled.model.RechiseledModel.bake(RechiseledModel.java:59) ~[rechiseled-1.0.12a-forge-mc1.19.3.jar%23161!/:?] {re:classloading}
-- Overlay render details --
Details:
	Overlay name: net.minecraft.client.gui.screens.LoadingOverlay
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:1351) ~[client-1.19.4-20230314.122934-srg.jar%23165!/:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1160) ~[client-1.19.4-20230314.122934-srg.jar%23165!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:731) ~[client-1.19.4-20230314.122934-srg.jar%23165!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[1.19.4-forge-45.0.40.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.4-45.0.40.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}


-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: No
	Packs: vanilla, mod_resources

-- System Details --
Details:
	Minecraft Version: 1.19.4
	Minecraft Version ID: 1.19.4
	Operating System: Linux (amd64) version 5.15.0-69-generic
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 339117288 bytes (323 MiB) / 671088640 bytes (640 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz
	Identifier: Intel64 Family 6 Model 58 Stepping 9
	Microarchitecture: Ivy Bridge (Client)
	Frequency (GHz): 3.20
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: Navi 14 [Radeon RX 5500/5500M / Pro 5500M]
	Graphics card #0 vendor: Advanced Micro Devices, Inc. [AMD/ATI] (0x1002)
	Graphics card #0 VRAM (MB): 258.00
	Graphics card #0 deviceId: 0x7340
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 20330.86
	Virtual memory used (MB): 5738.23
	Swap memory total (MB): 16384.00
	Swap memory used (MB): 886.11
	JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.19.4-forge-45.0.40
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: AMD Radeon RX 5500 XT (navi14, LLVM 15.0.7, DRM 3.42, 5.15.0-69-generic) GL version 4.6 (Core Profile) Mesa 23.0.1, AMD
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: en_au
	CPU: 4x Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz
	OptiFine Version: OptiFine_1.19.4_HD_U_I3
	OptiFine Build: 20230324-183832
	Render Distance Chunks: 20
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: ComplementaryReimagined_r2.0.3.zip
	OpenGlVersion: 4.6 (Core Profile) Mesa 23.0.1
	OpenGlRenderer: AMD Radeon RX 5500 XT (navi14, LLVM 15.0.7, DRM 3.42, 5.15.0-69-generic)
	OpenGlVendor: AMD
	CpuCount: 4
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.3.jar eventbus PLUGINSERVICE 
		fmlloader-1.19.4-45.0.40.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19.4-45.0.40.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19.4-45.0.40.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19.4-45.0.40.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19.4-45.0.40.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar OptiFine TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.19.4-20230314.122934-srg.jar             |Minecraft                     |minecraft                     |1.19.4              |ENQUEUE_IM|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		supermartijn642corelib-1.1.6-forge-mc1.19.4.jar   |SuperMartijn642's Core Lib    |supermartijn642corelib        |1.1.6               |ENQUEUE_IM|Manifest: NOSIGNATURE
		cloth-config-10.0.96-forge.jar                    |Cloth Config v10 API          |cloth_config                  |10.0.96             |ENQUEUE_IM|Manifest: NOSIGNATURE
		forge-1.19.4-45.0.40-universal.jar                |Forge                         |forge                         |45.0.40             |ENQUEUE_IM|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		supermartijn642configlib-1.1.6b-forge-mc1.19.jar  |SuperMartijn642's Config Libra|supermartijn642configlib      |1.1.6b              |ENQUEUE_IM|Manifest: NOSIGNATURE
		rechiseled-1.0.12a-forge-mc1.19.3.jar             |Rechiseled                    |rechiseled                    |1.0.12a             |ENQUEUE_IM|Manifest: NOSIGNATURE
		forgivingvoid-forge-1.19.4-9.0.1.jar              |Forgiving Void                |forgivingvoid                 |9.0.1               |ENQUEUE_IM|Manifest: NOSIGNATURE
		collective-1.19.4-6.54.jar                        |Collective                    |collective                    |6.54                |ENQUEUE_IM|Manifest: NOSIGNATURE
		treeharvester-1.19.4-8.0.jar                      |Tree Harvester                |treeharvester                 |8.0                 |ENQUEUE_IM|Manifest: NOSIGNATURE
		journeymap-1.19.4-5.9.4beta2-forge.jar            |Journeymap                    |journeymap                    |5.9.4beta2          |ENQUEUE_IM|Manifest: NOSIGNATURE
		balm-forge-1.19.3-5.0.4.jar                       |Balm                          |balm                          |5.0.4               |ENQUEUE_IM|Manifest: NOSIGNATURE
		jei-1.19.3-forge-12.4.0.22(1).jar                 |Just Enough Items             |jei                           |12.4.0.22           |ENQUEUE_IM|Manifest: NOSIGNATURE
	Crash Report UUID: a1b48946-b42b-460e-b2d3-d964c7f0def1
	FML: 45.0
	Forge: net.minecraftforge:45.0.40
```
Any and all help is appreciated.

**Comment by SuperMartijn642** [comment] 2023-04-01 20:30
Seems to be a duplicate of #25.

I only updated my core library specifically for 1.19.4. I simply marked all my mods as compatible with 1.19.4 in the hope I get reports if it does not. Mods of mods will indeed just work, but it seems Rechiseled is not one of them.
I will have to see when I have time to fix all the 1.19.4 issues.

**Closed as completed by SuperMartijn642** 2023-04-01 20:30 UTC
Labels: crash, duplicate
