### ISSUE TITLE
[Bug] Dupe Bug

### ISSUE THREAD

**Issue by Saereth** [SuperMartijn642/Rechiseled#27] opened 2023-04-09 17:58 UTC
**Version Info**
- Minecraft, 1.19.2
- Forge 43.2.6
- Rechiseled rechiseled-1.0.12a-forge-mc1.19

**Description of the Bug**
Originally reported here: https://github.com/FTBTeam/FTB-Modpack-Issues/issues/3005
when using the scroll wheel to move blocks to and from the inventory it dupes the item
Possible compat issue with mousetweaks?

**Steps to Reproduce**
get the chisel from Rechiseled
put in any block that can be chiseled
scroll up on the block in the chisel GUI to move items back, and watch it just dupe them

**Comment by SuperMartijn642** [comment] 2023-04-15 21:10
I cannot reproduce the issue. Both scrolling from my inventory to the chisel and from the chisel to my inventory seems to work as expected.

https://user-images.githubusercontent.com/12382965/232253236-5848ac4c-9509-46be-8f4c-b7c5dce7cbbb.mp4


Whoops, accidentally pressed 'close with comment'

**Comment by SmallSansSerif** [comment] 2023-04-26 19:29
I can confirm this is happening as well. It seems to be conflicting with Mousetweaks scroll wheel moving items back and forth from inventory to chisel.

**Comment by Saereth** [comment] 2023-04-26 19:31
yeah second report on the issue, https://github.com/FTBTeam/FTB-Modpack-Issues/issues/3177 definitely seems to be mousetweaks compat issue, but considering that's a clientside mod it would seem like something else isnt getting checked to prevent that

**Comment by SuperMartijn642** [comment] 2023-04-26 19:49
Like shown in my first comment, I cannot reproduce the issue.

@SmallSansSerif what versions of Minecraft, Rechiseled, and Mouse Tweaks are you using?

**Comment by SmallSansSerif** [comment] 2023-04-26 22:37
Minecraft, 1.19.2
Forge 43.2.8
Rechiseled: rechiseled-1.0.13-forge-mc1.19
Mousetweaks: MouseTweaks-forge-mc1.19-2.23

**Comment by SmallSansSerif** [comment] 2023-04-26 22:57
@SuperMartijn642 Created a clean install of just those mods and then add:

inventorysorter-1.19.2-21.0.4.jar

That seems to be the conflict for me.

**Comment by SuperMartijn642** [comment] 2023-05-03 10:25
Seems to be an issue with Inventory Sorter. I have created a pull request for it here: https://github.com/cpw/inventorysorter/pull/171.

**Comment by SuperMartijn642** [comment] 2023-09-05 13:05
Closing this as it is up to Inventory Sorter to now.
Thank you for reporting the issue!

**Closed as completed by SuperMartijn642** 2023-09-05 13:05 UTC
Labels: bug
