### ISSUE TITLE
[Bug] Chisels & Bits incompatability

### ISSUE THREAD

**Issue by MattB70** [SuperMartijn642/Rechiseled#9] opened 2022-07-01 07:16 UTC
**Version Info**
- Minecraft, 1.18.2
- Rechiseled, 1.0.10a
- Chisels & Bits, 1.2.101
- Forge 10.1.54

**Description of the Bug**
Using Chisels and Bits on a Rechiseled block now creates a texture bug. This issue is caused by the update to Chisels and Bits, but only occurs to blocks provided by this mod. This issue has halted progress on my projects. This should be reproducible.

**Steps to Reproduce**
Install:
![image](https://user-images.githubusercontent.com/43189368/176843879-1d498e0e-f5f1-434e-bad7-cacdae49697b.png)
Use Chisels and Bits on a Rechiseled block.

**Screenshots**
![image](https://user-images.githubusercontent.com/43189368/176844047-418dfa53-0dc6-4da5-9ce6-2a3eaefe10e1.png)

**Comment by marchermans** [comment] 2022-07-01 07:20
Hit me up when you want to look into this, and we will check it out together. @SuperMartijn642

**Comment by SuperMartijn642** [comment] 2022-07-02 18:22
I am currently busy with exams, so might be a bit before I have time to properly fix things.

From an initial look, the issue seems to come from [`ChiseledBlockBakedModel`](https://github.com/ChiselsAndBits/Chisels-and-Bits/blob/5f338bd3ea9e85cfac40c72c241b36770589da4f/common/src/main/java/mod/chiselsandbits/client/model/baked/chiseled/ChiseledBlockBakedModel.java) in Chisels & Bits assuming that a quad always uses the full texture.
This can be confirmed by using a model which uses only a part of the texture. For example, create a resource pack with the following model for `models/block/cobblestone.json`:
```json
{
  "parent": "block/block",
  "textures": {
    "particle": "#all",
    "all": "minecraft:block/cobblestone"
  },
  "elements": [
    {   "from": [ 0, 0, 0 ],
      "to": [ 16, 16, 16 ],
      "faces": {
        "down":  { "uv": [ 0, 0, 8, 8 ], "texture": "#all", "cullface": "down" },
        "up":    { "uv": [ 0, 0, 8, 8 ], "texture": "#all", "cullface": "up" },
        "north": { "uv": [ 0, 0, 8, 8 ], "texture": "#all", "cullface": "north" },
        "south": { "uv": [ 0, 0, 8, 8 ], "texture": "#all", "cullface": "south" },
        "west":  { "uv": [ 0, 0, 8, 8 ], "texture": "#all", "cullface": "west" },
        "east":  { "uv": [ 0, 0, 8, 8 ], "texture": "#all", "cullface": "east" }
      }
    }
  ]
}
```
Note the `uv` part for the faces to make it so the cobble only uses 1/4th of its texture.
This leads to following visuals in game:
![image](https://user-images.githubusercontent.com/12382965/177011653-f3614d78-7f89-4eef-a60f-e5d3a56b4fe1.png)
On the left is a regular cobblestone block and on the right is a cobblestone block with one bit missing. As you can see the right block has the same issue as the blocks from Rechiseled. This example occurs with just Chisels & Bits installed.

The assumption made by Chisels & Bits is most easily visible in [`BitBlockBakedModel`](https://github.com/ChiselsAndBits/Chisels-and-Bits/blob/5f338bd3ea9e85cfac40c72c241b36770589da4f/common/src/main/java/mod/chiselsandbits/client/model/baked/bit/BitBlockBakedModel.java).
The `getFaceUvs` method always returns values 7 and 8.
```java
private float[] getFaceUvs(final Direction face)
{
        ...
        final int from_x = 7;
        final int from_y = 7;
        final int from_z = 7;

        final int to_x = 8;
        final int to_y = 8;
        final int to_z = 8;
        ...
}
```
These values are then directly used by the following [line in its constructor](https://github.com/ChiselsAndBits/Chisels-and-Bits/blob/5f338bd3ea9e85cfac40c72c241b36770589da4f/common/src/main/java/mod/chiselsandbits/client/model/baked/bit/BitBlockBakedModel.java#L96) as the uv values for the texture.
```java
generic.add(faceBakery.bakeQuad(toB, fromB, bpf, quadLayer.getSprite(), myFace, mr, null, false, new ResourceLocation(Constants.MOD_ID, "bit")));
```
Here the uv values from the original quad are ignored. Basically, it will always take 7/16th and 8/16th of the entire texture instead of 7/16th and 8/16th of the uv values specified by the original quad.

[`ChiseledBlockBakedModel`](https://github.com/ChiselsAndBits/Chisels-and-Bits/blob/5f338bd3ea9e85cfac40c72c241b36770589da4f/common/src/main/java/mod/chiselsandbits/client/model/baked/chiseled/ChiseledBlockBakedModel.java) has the same issue, where it ignores the uv values from the original quad.

**Comment by marchermans** [comment] 2022-07-02 19:33
> I am currently busy with exams, so might be a bit before I have time to properly fix things.
> 
> From an initial look, the issue seems to come from [`ChiseledBlockBakedModel`](https://github.com/ChiselsAndBits/Chisels-and-Bits/blob/5f338bd3ea9e85cfac40c72c241b36770589da4f/common/src/main/java/mod/chiselsandbits/client/model/baked/chiseled/ChiseledBlockBakedModel.java) in Chisels & Bits assuming that a quad always uses the full texture. This can be confirmed by using a model which uses only a part of the texture. For example, create a resource pack with the following model for `models/block/cobblestone.json`:
> 
> ```json
> {
>   "parent": "block/block",
>   "textures": {
>     "particle": "#all",
>     "all": "minecraft:block/cobblestone"
>   },
>   "elements": [
>     {   "from": [ 0, 0, 0 ],
>       "to": [ 16, 16, 16 ],
>       "faces": {
>         "down":  { "uv": [ 0, 0, 8, 8 ], "texture": "#all", "cullface": "down" },
>         "up":    { "uv": [ 0, 0, 8, 8 ], "texture": "#all", "cullface": "up" },
>         "north": { "uv": [ 0, 0, 8, 8 ], "texture": "#all", "cullface": "north" },
>         "south": { "uv": [ 0, 0, 8, 8 ], "texture": "#all", "cullface": "south" },
>         "west":  { "uv": [ 0, 0, 8, 8 ], "texture": "#all", "cullface": "west" },
>         "east":  { "uv": [ 0, 0, 8, 8 ], "texture": "#all", "cullface": "east" }
>       }
>     }
>   ]
> }
> ```
> 
> Note the `uv` part for the faces to make it so the cobble only uses 1/4th of its texture. This leads to following visuals in game: ![image](https://user-images.githubusercontent.com/12382965/177011653-f3614d78-7f89-4eef-a60f-e5d3a56b4fe1.png) On the left is a regular cobblestone block and on the right is a cobblestone block with one bit missing. As you can see the right block has the same issue as the blocks from Rechiseled. This example occurs with just Chisels & Bits installed.
> 
> The assumption made by Chisels & Bits is most easily visible in [`BitBlockBakedModel`](https://github.com/ChiselsAndBits/Chisels-and-Bits/blob/5f338bd3ea9e85cfac40c72c241b36770589da4f/common/src/main/java/mod/chiselsandbits/client/model/baked/bit/BitBlockBakedModel.java). The `getFaceUvs` method always returns values 7 and 8.
> 
> ```java
> private float[] getFaceUvs(final Direction face)
> {
>         ...
>         final int from_x = 7;
>         final int from_y = 7;
>         final int from_z = 7;
> 
>         final int to_x = 8;
>         final int to_y = 8;
>         final int to_z = 8;
>         ...
> }
> ```
> 
> These values are then directly used by the following [line in its constructor](https://github.com/ChiselsAndBits/Chisels-and-Bits/blob/5f338bd3ea9e85cfac40c72c241b36770589da4f/common/src/main/java/mod/chiselsandbits/client/model/baked/bit/BitBlockBakedModel.java#L96) as the uv values for the texture.
> 
> ```java
> generic.add(faceBakery.bakeQuad(toB, fromB, bpf, quadLayer.getSprite(), myFace, mr, null, false, new ResourceLocation(Constants.MOD_ID, "bit")));
> ```
> 
> Here the uv values from the original quad are ignored. Basically, it will always take 7/16th and 8/16th of the entire texture instead of 7/16th and 8/16th of the uv values specified by the original quad.
> 
> [`ChiseledBlockBakedModel`](https://github.com/ChiselsAndBits/Chisels-and-Bits/blob/5f338bd3ea9e85cfac40c72c241b36770589da4f/common/src/main/java/mod/chiselsandbits/client/model/baked/chiseled/ChiseledBlockBakedModel.java) has the same issue, where it ignores the uv values from the original quad.

That is a weird behaviour... Cause i extract the UVs from the BakedQuad and then interpolate.
I will investigate....

**Comment by marchermans** [comment] 2022-07-02 19:58
Found the bug.
I payed attention to not make that assumption, but still did in one particular case.... Sadface panda.

Will push an update.

**Comment by SuperMartijn642** [comment] 2022-07-02 21:15
> I payed attention to not make that assumption, but still did in one particular case.... Sadface panda.

I can definitely relate to that feeling xD

Also, not entirely sure if this is the reason it broke with Rechiseled, since the effect did look a bit different. Might still just be some jank with Rechiseled's baked model, but I guess I'll have to see.

**Comment by marchermans** [comment] 2022-07-03 18:25
No clue, the effect happens because it fails to properly interpolate.
@MattB70 Can you retest with the latest version of C&B so we could potentially close this issue?

**Comment by MattB70** [comment] 2022-07-03 18:42
Fixed!

I also noticed the reduced quads being drawn on the inside of blocks. Awesome changes, thanks :)

**Comment by MattB70** [comment] 2022-07-03 18:48
I spoke too soon.

It still happens but much less frequently. Now it seems to only occur on 1/4 sized blocks or smaller. Attached are some examples.

_1/4 sized blocks are bugged, also note how some of them are not in the flickering state but are distorted such as the textures towards the bottom of the image._
![image](https://user-images.githubusercontent.com/43189368/177053184-fa98d8cc-98dd-41ad-a83a-38bad930aeb3.png)

_Again, some render distorted while others render with flickering banding._
![image](https://user-images.githubusercontent.com/43189368/177053219-38f9257e-4341-4f84-a4ec-e9c8dff44e7d.png)

_Here you can see how any block with 1/4 or smaller sized faces are distorted, such as the raised floor beneath this table._
![image](https://user-images.githubusercontent.com/43189368/177053432-aecdd07e-7a24-49ff-a757-223365185727.png)

**Comment by marchermans** [comment] 2022-07-04 10:23
> ```json
> {
>   "parent": "block/block",
>   "textures": {
>     "particle": "#all",
>     "all": "minecraft:block/cobblestone"
>   },
>   "elements": [
>     {   "from": [ 0, 0, 0 ],
>       "to": [ 16, 16, 16 ],
>       "faces": {
>         "down":  { "uv": [ 0, 0, 8, 8 ], "texture": "#all", "cullface": "down" },
>         "up":    { "uv": [ 0, 0, 8, 8 ], "texture": "#all", "cullface": "up" },
>         "north": { "uv": [ 0, 0, 8, 8 ], "texture": "#all", "cullface": "north" },
>         "south": { "uv": [ 0, 0, 8, 8 ], "texture": "#all", "cullface": "south" },
>         "west":  { "uv": [ 0, 0, 8, 8 ], "texture": "#all", "cullface": "west" },
>         "east":  { "uv": [ 0, 0, 8, 8 ], "texture": "#all", "cullface": "east" }
>       }
>     }
>   ]
> }
> ```

I can't reproduce this anymore on my side:
![image](https://user-images.githubusercontent.com/5585406/177135229-fd068db6-ecbc-4f27-a578-3bf573641ada.png)

These are the 1/4, 1/8 and single bits, with the model from @SuperMartijn642 from above, as you can see no visual artifacts are visible.

Not sure what the cause here is then now.

That artifact which you see occurs if C&B is not able to properly detect the corners of the texture and then assigns two vertexes of a face the same value. But I am not sure what the cause is now.

**Comment by MattB70** [comment] 2022-07-04 18:31
My environment (forge 40.1.54):
![image](https://user-images.githubusercontent.com/43189368/177204063-6b3472d9-0c56-4e38-aebe-c19a1c056af5.png)

Result:
![image](https://user-images.githubusercontent.com/43189368/177204039-bf1904d9-ddba-447b-9ae7-1fc099b80c13.png)

The behavior here makes me think it may be related to the new culling of hidden faces, but I can't be sure. I'm also not sure why it seems to not happen for you. Is there a version mismatch somewhere in my environment?

**Comment by SuperMartijn642** [comment] 2022-07-04 19:09
Note that OrionDevelopment was talking about the vannilla example now working correctly.
The issues you're experiencing still, MattB70, are specifically Rechiseled. Probably just something weird caused by Rechiseled's baked models, but I'll have to look into it when I have more time.

**Comment by SuperMartijn642** [comment] 2022-07-07 11:05
@OrionDevelopment still seems to be some weirdness going on with the vanilla example when removing certain bits. Although not entirely sure what problem is this time from looking at the code.

https://user-images.githubusercontent.com/12382965/177758953-1c887277-e906-4b2a-a82f-686991002763.mp4

**Comment by marchermans** [comment] 2022-07-07 20:54
Okey.... More I need to debug there still seems to be a corner case where UVs are not properly extracted from their source and interpolated properly.

**Closed as completed** 2023-04-15 20:50 UTC
Labels: bug
