### ISSUE TITLE
[Feature/Bug] Scrollbar / Pagination

### ISSUE THREAD

**Issue by MJRamon** [SuperMartijn642/Rechiseled#90] opened 2024-05-11 18:51 UTC
If amount of blocks is above hardcoded 25, they could never be crafted with chisel (for ex., added new blocks by datapacks).

There are feature requests:

https://github.com/SuperMartijn642/Rechiseled/issues/75
https://github.com/SuperMartijn642/Rechiseled/issues/70

**Describe the solution you'd like**
There's already a pull request for this:

https://github.com/SuperMartijn642/Rechiseled/pull/82

Fabric request also (as well as REI support would be great).

**Comment by SuperMartijn642** [comment] 2024-05-11 20:47
There's already an issue for this, like you mentioned... 🤔
I will close the issue then as it is indeed a duplicate of #70.

> Fabric request also

What do you mean by that?

**Closed as completed by SuperMartijn642** 2024-05-11 20:47 UTC
Labels: feature request
