### ISSUE TITLE
[Bug] Weird textures and missing ones.

### ISSUE THREAD

**Issue by Ianzukito** [SuperMartijn642/Rechiseled#64] opened 2023-11-05 14:14 UTC
1.20.1, Forge
- Minecraft, 1.20.1
- Rechiseled, 1.1.5b

**Description of the Bug**
i open my inventory to see the rechiseled options, and all of the rechiseled added blocks have missing textures and errors.

**Steps to Reproduce**
i have rechiseled, rechiseled: create, modernfix, fusion and embeddium all on their latest versions.

**Screenshots**
![image](https://github.com/SuperMartijn642/Rechiseled/assets/30326517/228990dd-6225-4f03-af2d-a0f4957e8269)

**Comment by SuperMartijn642** [comment] 2023-11-05 14:17
This is likely caused by a combination with some other mod (besides ModernFix and Embeddium). Could you narrow down what mods are needed to reproduce the issue?

**Comment by Ianzukito** [comment] 2023-11-05 14:23
> This is likely caused by a combination with some other mod (besides ModernFix and Embeddium). Could you narrow down what mods are needed to reproduce the issue?

i really dont know what i could do or search for this, i can send you the whole mods list tho

**Comment by Ianzukito** [comment] 2023-11-05 14:27
i can see thats just when it is connecting that this bug happens
![image](https://github.com/SuperMartijn642/Rechiseled/assets/30326517/87e0f6bf-719c-4b8d-9b56-a00dc6df1d4e)

**Comment by SuperMartijn642** [comment] 2023-11-05 14:29
Just disable half the mods (besides Rechiseled and Fusion) at a time. If the issue persists, continue with the mods you have left. If the issue goes away, continue with the mods you removed.
Then just repeat until you find the one mod that triggers it.

For a set of 100 mods, you would need to do this just 7 times to find the culprit.

Also, what version of Fusion are you using? If it is not the latest, make sure to update it and check if the issue persists.

**Comment by Ianzukito** [comment] 2023-11-05 14:31
i can do that, my modpack has 150ish mods...

i'm using the latest version of fusion and rechiseled, i downloaded them today

**Comment by Ianzukito** [comment] 2023-11-05 15:01
> Just disable half the mods (besides Rechiseled and Fusion) at a time. If the issue persists, continue with the mods you have left. If the issue goes away, continue with the mods you removed. Then just repeat until you find the one mod that triggers it.
> 
> For a set of 100 mods, you would need to do this just 7 times to find the culprit.
> 
> Also, what version of Fusion are you using? If it is not the latest, make sure to update it and check if the issue persists.

i'm really tryind to find the problem, but i cant find it...
![image](https://github.com/SuperMartijn642/Rechiseled/assets/30326517/bb3d6e02-a8ab-4d14-83a6-64acae669ce6)
this error repeats many, many times in the log when launching the game, can it be of some help?
![image](https://github.com/SuperMartijn642/Rechiseled/assets/30326517/e3307314-91ba-4e90-b78d-47d518091c64)
then this one repeats

**Comment by SuperMartijn642** [comment] 2023-11-05 15:03
Hmm you are using the correct Fusion right? https://www.curseforge.com/minecraft/mc-mods/fusion-connected-textures

**Comment by Ianzukito** [comment] 2023-11-05 15:05
> Hmm you are using the correct Fusion right? https://www.curseforge.com/minecraft/mc-mods/fusion-connected-textures

yes!
![image](https://github.com/SuperMartijn642/Rechiseled/assets/30326517/bf7a5faf-4509-4a2e-a966-f0c3b5c77059)

**Comment by SuperMartijn642** [comment] 2023-11-05 17:03
> i have rechiseled, rechiseled: create, modernfix, fusion and embeddium all on their latest versions.

I just tested it and it works fine with just those mods installed.

It must be caused by some other mod you have installed. You'll have to narrow down which mod that is.

**Comment by Cguy7777** [comment] 2023-11-10 07:26
I recently experienced a similar glitch, which I resolved by removing a mod called [Fusion](https://legacy.curseforge.com/minecraft/mc-mods/fusion), not to be confused with the Rechiseled dependency of the same name. It seems that if both are installed, the one Rechiseled needs doesn't get loaded.

**Comment by SuperMartijn642** [comment] 2023-11-12 10:59
>I recently experienced a similar glitch, which I resolved by removing a mod called Fusion

Yup, that mod happens to have the same mod modid and its version number is higher than the one required by Rechiseled. Forge thinks they are the same mod and only loads the one with the higher version number.

**Closed as completed by SuperMartijn642** 2023-11-12 10:59 UTC
Labels: bug
