### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by SafTheLamb** [SuperMartijn642/Rechiseled#93] opened 2024-06-10 00:18 UTC
**Version Info**
- Minecraft, 1.20.1
- Rechiseled, 1.1.6
- Fusion, 1.1.1

**What mod loader are you using?**: Quilt

**Description of the Bug**
Pressing ESC or closing Inventory while using Chisel breaks GUI, you can look around with mouse, but cannot move or do anything.

**Steps to Reproduce**
Right click with Chisel
Press ESC to close inventory
Observe

If this isn't replicated, I can narrow down if any other mods I have installed are causing issues.

**Comment by SuperMartijn642** [comment] 2024-06-10 02:28
This version of Rechiseled has been out for quite a while and I have not had any reports of such a major issue, so I would have to guess it is caused by a combination with some other mod.
If you could narrow down which other mod is needed to reproduce the issue that would be appreciated.

**Comment by SafTheLamb** [comment] 2024-06-10 17:36
OK I figured out, it's the Flow mod that breaks it. https://modrinth.com/mod/flow I've disabled it for myself, and will also post a bug for them, since idk which mod should add compat between the two of them.

**Comment by SafTheLamb** [comment] 2024-06-10 17:36
Oh someone found a fix already too! https://github.com/IMB11/Flow/issues/26 so like, it'd be nice to have smooth menu animations with Chisel, but not a big deal at all, ty!

**Comment by SuperMartijn642** [comment] 2024-08-15 11:07
This has now been fixed by Flow.
Thank you for reporting the issue!

**Closed as completed by SuperMartijn642** 2024-08-15 11:07 UTC
Labels: bug
