### ISSUE TITLE
[Bug] newest update breaks textures

### ISSUE THREAD

**Issue by Leclowndu93150** [SuperMartijn642/Rechiseled#36] opened 2023-06-20 09:08 UTC
**Version Info**
- Minecraft, 1.19.2
- Rechiseled, latest 
![javaw_5Fe8VhlIZE](https://github.com/SuperMartijn642/Rechiseled/assets/73310949/5e496a0a-473b-471e-a49c-5f7637781d5d)

**Comment by SuperMartijn642** [comment] 2023-06-20 09:26
It works fine with just Rechiseled.

Are you using any other mods? If so, could you narrow down which mods are needed to reproduce the issue?

**Comment by Leclowndu93150** [comment] 2023-06-20 15:53
https://pastebin.com/HjHRQZrr here

i can even send  you the modpack if you dont mind

**Comment by embeddedt** [comment] 2023-06-20 20:06
It's probably ModernFix. [This mixin](https://github.com/SuperMartijn642/Fusion/blob/forge-1.16/src/main/java/com/supermartijn642/fusion/mixin/TextureAtlasMixin.java) will not work correctly unless faster texture loading is disabled in ModernFix's config, as `getBasicSpriteInfos` is changed to read and cache the full image instead of using `PngSizeInfo`/`PngInfo`, which will bypass your change. This is similar to how Mojang handles textures in 1.19.3 and later.

Is it possible to avoid mixing into the texture atlas in Fusion? `PngSizeInfo` really slows down texture loading, so launch time will be impacted if I need to disable my optimization here when Fusion is present.

I think it should also be safe to do the replacement when `getLoadedSprites` returns instead of within `getBasicSpriteInfos`.

**Comment by SuperMartijn642** [comment] 2023-06-20 22:29
> changed to read and cache the full image

Ah I was already confused when I saw vanilla loaded each texture just to get the size and then discarded it lol

The problem I have now is that I need access to the texture metadata so I can load Fusion's metadata. Vanilla already loads the metadata for each texture which then gets cached in `Resource`. I would preferably not have to re-request the resource, since that would lead to me having to read the metadata file from disk a second time.

I can move it to `getLoadedSprites` and re-request the resource and load the metadata again, but I don't know if that's worth it performance wise. Maybe you know if that's worth it (or if there's another solution)?

**Comment by embeddedt** [comment] 2023-06-21 01:10
> Ah I was already confused when I saw vanilla loaded each texture just to get the size and then discarded it lol

Indeed, the number of puzzling design choices like this is incredible.

> I can move it to `getLoadedSprites` and re-request the resource and load the metadata again, but I don't know if that's worth it performance wise. Maybe you know if that's worth it (or if there's another solution)?

I think that is the cleanest solution. The only other approach I see would be for me to modify my mixin so that it doesn't completely replace `getBasicSpriteInfos`, but that requires injecting into a lambda which has generally been annoying to do in a way that works across modloaders and MC versions without a lot of fiddling.

You can parallelize it using Mojang's `Util.backgroundExecutor()` which should hopefully make it fast enough; generally speaking more time seems to be spent reading the full contents of resources than opening them.

**Comment by SuperMartijn642** [comment] 2023-06-21 17:24
Should be fixed now in version 1.0.1 of Fusion.
Thanks for the help!

**Closed as completed by SuperMartijn642** 2023-06-21 17:24 UTC
Labels: bug

**Comment by embeddedt** [comment] 2023-06-23 14:07
I think you applied the compatibility to a few too many versions. As of 1.19.3 Mojang finally fixed the texture system themselves so ModernFix no longer patches it, and your normal mixin should work fine. Someone reported https://github.com/embeddedt/ModernFix/issues/140 which seems to be caused by applying the ModernFix-specific mixin.

**Comment by SuperMartijn642** [comment] 2023-06-23 14:46
Not sure what's going on, I only added the ModernFix stuff to 1.19.2 and below. It isn't even present on the 1.20 branch 🤔

**Comment by embeddedt** [comment] 2023-06-23 14:48
Weird, I will ask them to check they installed the correct version.

**Comment by Leclowndu93150** [comment] 2023-06-23 21:40
im fascinated by all this chinese

**Comment by P3rf3ctXZer0** [comment] 2023-07-21 06:46
I am using 1.16.5 and it is definitely an issue.
